version: '3.6'
services:
  integration-test:
    build:
      context: .
      target: test
    depends_on:
      - avro-schemas.kafka
    environment:
      SCHEMA_REGISTRY_URL: avro-schemas.kafka:9092
      BROKER_LIST: kafka:9092
  kafka:
    image: quay.io/parkhubprime/ph-confluent-kafka:4.1.2
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      BROKER_ID_COMMAND: "hostname | awk -F'-' '{print $$2}'"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: quay.io/parkhubprime/ph-confluent-zookeeper:4.1.2
    hostname: zookeeper
    environment:
      ZOOKEEPER_REPLICAS: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_PORT: 2888
      ZOOKEEPER_ELECTION_PORT: 3888
  avro-schemas.kafka:
    image: confluentinc/cp-schema-registry:4.1.2
    hostname: avro-schemas.kafka
    ports: 
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: avro-schemas.kafka 
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - kafka
      - zookeeper
